import type { Metadata } from 'next';
import { Inter, Montserrat_Subrayada } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const montserratSubrayada = Montserrat_Subrayada({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-montserrat-subrayada',
});

export const metadata: Metadata = {
  title: 'Collection App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${inter.variable} ${montserratSubrayada.variable}`}
    >
      <head>
        <link rel='icon' type='image/png' sizes='32x32' href='/favicon.png' />
      </head>
      <body>{children}</body>
    </html>
  );
}
